# Generated by Django 4.0 on 2022-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart_id',
            field=models.BigIntegerField(null=True, verbose_name='部门ID'),
        ),
    ]
