# Generated by Django 4.0 on 2022-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(max_length=64, verbose_name='年龄')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(max_length=64, verbose_name='入职时间')),
                ('depart_id', models.BigIntegerField(max_length=64, verbose_name='部门ID')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], max_length=16, verbose_name='性别')),
            ],
        ),
    ]
