# Generated by Django 4.0 on 2022-10-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_userinfo_age_alter_userinfo_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart_id',
            field=models.BigIntegerField(verbose_name='所属部门'),
        ),
    ]
